multierror: new error type to wrap multiple causes
Go 1.20 introduced the concept of multiple causes attached to an error
object. In order to properly extend our errors library to deal with
these new error types, this commit introduces the `MultiError` struct
which is simply a container of an array of errors.

Additionally, we introduce new protobuf messages to facilitate
encoding these multi-cause errors.

Errors can now be "unwrapped" into a `MultiError` and the encode/
decode functionality knows what to do with those types: traverse the
causes and encode them into a list.

Additionally, the `Is()` and `As()` methods have been extended to
traverse the multi-error causes in a depth-first manner.